---
jira:
  projectKey: "HBX"
  ignore:
    - user: dependabot[bot]
      titlePattern: "Bump.*+"
branches:
  enabled: true
  label: "%s"
  ignore:
    # We ignore all dependabot PRs branch labels:
    - user: dependabot[bot]
      titlePattern: "Bump.*+"
