CREATE TABLE CLASSA ( id INT NOT NULL PRIMARY KEY, myClassB INT NOT NULL );
CREATE TABLE CLASSB ( id INT NOT NULL PRIMARY KEY, myType VARCHAR(255), name VARCHAR(255), valueA VARCHAR(255), valueB VARCHAR(255));
CREATE TABLE CLASSC ( id INT NOT NULL PRIMARY KEY, myClassB INT NOT NULL )