CREATE SCHEMA HTT
CREATE TABLE HTT.GROUPS (NAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME))
CREATE TABLE HTT.USERS (NAME VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255), GROUPNAME VARCHAR(255), PRIMARY KEY (NAME), FOREIGN KEY (GROUPNAME) REFERENCES HTT.GROUPS(NAME))
CREATE TABLE HTT.SESSION_ATTRIBUTES (ID INT NOT NULL, NAME VARCHAR(255) NOT NULL, STRINGDATA VARCHAR(255), USERNAME VARCHAR(255) NOT NULL, PRIMARY KEY (ID), FOREIGN KEY (USERNAME) REFERENCES HTT.USERS(NAME))