CREATE SCHEMA HTT
CREATE TABLE HTT.TAB_MASTER ( ID CHAR NOT NULL, NAME VARCHAR(20), PRIMARY KEY (ID) )
CREATE TABLE HTT.TAB_CHILD  ( CHILDID CHARACTER NOT NULL, MASTERREF CHAR, PRIMARY KEY (CHILDID), FOREIGN KEY (MASTERREF) REFERENCES HTT.TAB_MASTER(ID) )