/**
<#if groovy??>${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2groovy", 0)}<#else>${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2java", 0)}</#if> 
 */
<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} ${pojo.getExtendsDeclaration()} ${pojo.getImplementsDeclaration()}