CREATE TABLE USERS ( ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY(ID))
CREATE USER OTHERSCHEMA IDENTIFIED BY OTHERSCHEMA 
GRANT ALL PRIVILEGES TO OTHERSCHEMA WITH ADMIN OPTION
CREATE USER THIRDSCHEMA IDENTIFIED BY THIRDSCHEMA 
GRANT ALL PRIVILEGES TO THIRDSCHEMA WITH ADMIN OPTION
CREATE TABLE OTHERSCHEMA.ROLE ( ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY(ID))
GRANT REFERENCES ON OTHERSCHEMA.ROLE TO THIRDSCHEMA
GRANT REFERENCES ON USERS TO THIRDSCHEMA
CREATE TABLE THIRDSCHEMA.USERROLES ( USERID INT NOT NULL, ROLEID INT NOT NULL, PRIMARY KEY(USERID, ROLEID), FOREIGN KEY (ROLEID) REFERENCES OTHERSCHEMA.ROLE(ID), FOREIGN KEY (USERID) REFERENCES USERS(ID))
CREATE TABLE PLAINROLE ( ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY(ID))
CREATE TABLE PLAINUSERROLES ( USERID INT NOT NULL, ROLEID INT NOT NULL, PRIMARY KEY(USERID, ROLEID), FOREIGN KEY (ROLEID) REFERENCES PLAINROLE(ID), FOREIGN KEY (USERID) REFERENCES USERS(ID))