CREATE SCHEMA HTT
CREATE TABLE HTT.with_identity (id INT NOT NULL IDENTITY(1,1), data varchar(100),CONSTRAINT PK_identity PRIMARY KEY (id))
CREATE TABLE HTT.with_guid (uid UNIQUEIDENTIFIER DEFAULT newid() NOT NULL, data varchar(100), CONSTRAINT PK_guid PRIMARY KEY (uid))
