CREATE TABLE ORDERS (ID NUMBER(8) NOT NULL, NAME VARCHAR(20), PRIMARY KEY (ID))
CREATE TABLE ITEM  (CHILD_ID NUMBER(8) NOT NULL, NAME VARCHAR(50), ORDER_ID NUMBER, RELATED_ORDER_ID NUMBER, PRIMARY KEY (CHILD_ID), FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID), FOREIGN KEY (RELATED_ORDER_ID) REFERENCES ORDERS(ID) )
