package org.hibernate.tool.ant.GenericExport;

import java.io.File;

import org.hibernate.tools.test.util.AntUtil;
import org.hibernate.tools.test.util.FileUtil;
import org.hibernate.tools.test.util.JdbcUtil;
import org.hibernate.tools.test.util.ResourceUtil;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class TestCase {
	
	@Rule
	public TemporaryFolder temporaryFolder = new TemporaryFolder();
	
	private File destinationDir = null;
	private File resourcesDir = null;
	
	@Before
	public void setUp() {
		destinationDir = new File(temporaryFolder.getRoot(), "destination");
		destinationDir.mkdir();
		resourcesDir = new File(temporaryFolder.getRoot(), "resources");
		resourcesDir.mkdir();
		JdbcUtil.createDatabase(this);
	}
	
	@After
	public void tearDown() {
		JdbcUtil.dropDatabase(this);
	}
	
	@Test
	public void testGenericExport() {

		String[] resources = new String[] {"build.xml", "TopDown.hbm.xml", "generic-class.ftl"};
		ResourceUtil.createResources(this, resources, resourcesDir);
		File buildFile = new File(resourcesDir, "build.xml");	
		ResourceUtil.createResources(this, new String[] { "/hibernate.properties" }, resourcesDir);
		
		AntUtil.Project project = AntUtil.createProject(buildFile);
		project.setProperty("destinationDir", destinationDir.getAbsolutePath());
		project.setProperty("resourcesDir", resourcesDir.getAbsolutePath());
		
		File xTopDownJava = new File(destinationDir, "Xorg/hibernate/tool/hbm2x/ant/TopDown.java");
		Assert.assertFalse(xTopDownJava.exists());
		
		File topDownJava = new File(destinationDir, "org/hibernate/tool/hbm2x/ant/TopDown.java");
		Assert.assertFalse(topDownJava.exists());		

		File topDownQuote = new File(destinationDir, "org/hibernate/tool/hbm2x/ant/TopDown.quote");
		Assert.assertFalse(topDownQuote.exists());		

		File topDownPojo = new File(destinationDir, "org/hibernate/tool/hbm2x/ant/TopDown.pojo");
		Assert.assertFalse(topDownPojo.exists());		

		project.executeTarget("testGenericExport");
		
		Assert.assertTrue(xTopDownJava.exists());
		Assert.assertTrue(FileUtil
				.findFirstString("TopDown", xTopDownJava)
				.contains("TopDown generated by hbm2java"));

		Assert.assertTrue(topDownJava.exists());
		Assert.assertTrue(FileUtil
				.findFirstString("TopDown", topDownJava)
				.contains("TopDown generated by hbm2java"));

		Assert.assertTrue(topDownQuote.exists());
		Assert.assertTrue(FileUtil
				.findFirstString("TopDown", topDownQuote)
				.contains("pojo=TopDown"));

		Assert.assertTrue(topDownPojo.exists());
		Assert.assertTrue(FileUtil
				.findFirstString("TopDown", topDownPojo)
				.contains("TopDown generated by hbm2java"));

	}
	
	
}
