ALTER TABLE HTT.PROJECT DROP CONSTRAINT PROJECT_MANAGER
DROP TABLE HTT.WORKS_ON
DROP TABLE HTT.EMPLOYEE
DROP TABLE HTT.PROJECT
DROP TABLE HTT.ADDRESS_PERSON
DROP TABLE HTT.PERSON
DROP TABLE HTT.ADDRESS_MULTI_PERSON
DROP TABLE HTT.MULTI_PERSON
DROP SCHEMA HTT