CREATE SCHEMA HTT
CREATE TABLE HTT.SERIALIZABLE_RESULT ( ID VARCHAR(255) NOT NULL, LENGTH INT NOT NULL, PRIMARY KEY (ID) )
INSERT INTO HTT.SERIALIZABLE_RESULT VALUES ( 'First', 1023)
INSERT INTO HTT.SERIALIZABLE_RESULT VALUES ( 'Second', 2047)
CREATE TABLE HTT.OBJECT_RESULT ( ID VARCHAR(255) NOT NULL, LENGTH INT NOT NULL, PRIMARY KEY (ID) )
INSERT INTO HTT.OBJECT_RESULT VALUES ( 'Third', 4095)
INSERT INTO HTT.OBJECT_RESULT VALUES ( 'Fourth', 8181)
