CREATE SCHEMA HTT
CREATE TABLE HTT.LEFT_TABLE ( ID INT NOT NULL, PRIMARY KEY (ID) )
CREATE TABLE HTT.RIGHT_TABLE ( ID INT NOT NULL, PRIMARY KEY (ID) )
CREATE TABLE HTT.MIDDLE_TABLE ( LEFT_ID INT NOT NULL, RIGHT_ID INT NOT NULL, PRIMARY KEY (LEFT_ID), CONSTRAINT FK_MIDDLE_LEFT FOREIGN KEY (LEFT_ID) REFERENCES HTT.LEFT_TABLE, CONSTRAINT FK_MIDDLE_RIGHT FOREIGN KEY (RIGHT_ID) REFERENCES HTT.RIGHT_TABLE)
CREATE TABLE HTT.PERSON ( PERSON_ID INT NOT NULL, NAME VARCHAR(50), PRIMARY KEY (PERSON_ID) )
CREATE TABLE HTT.ADDRESS_PERSON ( ADDRESS_ID INT NOT NULL, NAME VARCHAR(50), PRIMARY KEY (ADDRESS_ID), CONSTRAINT FK_ADDRESS_PERSON FOREIGN KEY (ADDRESS_ID) REFERENCES HTT.PERSON)
CREATE TABLE HTT.MULTI_PERSON ( PERSON_ID INT NOT NULL, PERSON_COMPID INT NOT NULL, NAME VARCHAR(50), PRIMARY KEY (PERSON_ID, PERSON_COMPID) )
CREATE TABLE HTT.ADDRESS_MULTI_PERSON ( ADDRESS_ID INT NOT NULL, ADDRESS_COMPID INT NOT NULL, NAME VARCHAR(50), PRIMARY KEY (ADDRESS_ID, ADDRESS_COMPID), CONSTRAINT FK_ADDRESS_MULTI_PERSON FOREIGN KEY (ADDRESS_ID, ADDRESS_COMPID) REFERENCES HTT.MULTI_PERSON)		
