DROP TABLE HTT.MIDDLE_TABLE
DROP TABLE HTT.LEFT_TABLE
DROP TABLE HTT.RIGHT_TABLE
DROP TABLE HTT.ADDRESS_PERSON
DROP TABLE HTT.PERSON
DROP TABLE HTT.ADDRESS_MULTI_PERSON
DROP TABLE HTT.MULTI_PERSON
DROP SCHEMA HTT