CREATE SCHEMA HTT
CREATE TABLE HTT.SIMPLE_LINE_ITEM (LINE_ITEM_ID VARCHAR(256) NOT NULL, CUSTOMER_ORDER_ID_REF VARCHAR(256), PRODUCT_ID VARCHAR(256) NOT NULL, EXTRA_ID VARCHAR(256) NOT NULL, QUANTITY FLOAT, PRIMARY KEY (LINE_ITEM_ID))
CREATE TABLE HTT.PRODUCT (PRODUCT_ID VARCHAR(256) NOT NULL, EXTRA_ID VARCHAR(256) NOT NULL, DESCRIPTION VARCHAR(256) NOT NULL, PRICE FLOAT, NUMBER_AVAILABLE FLOAT, PRIMARY KEY (PRODUCT_ID, EXTRA_ID))
CREATE TABLE HTT.CUSTOMER (CUSTOMER_ID VARCHAR(256) NOT NULL, NAME VARCHAR(256) NOT NULL, ADDRESS VARCHAR(256) NOT NULL, PRIMARY KEY (CUSTOMER_ID))
CREATE TABLE HTT.SIMPLE_CUSTOMER_ORDER (CUSTOMER_ORDER_ID VARCHAR(256) NOT NULL, CUSTOMER_ID VARCHAR(256) NOT NULL, ORDER_NUMBER FLOAT NOT NULL, ORDER_DATE DATE NOT NULL, PRIMARY KEY (CUSTOMER_ORDER_ID))
ALTER TABLE HTT.SIMPLE_LINE_ITEM ADD CONSTRAINT TO_SIMPLE_CUSTOMER_ORDER FOREIGN KEY (CUSTOMER_ORDER_ID_REF) REFERENCES HTT.SIMPLE_CUSTOMER_ORDER
ALTER TABLE HTT.SIMPLE_LINE_ITEM ADD CONSTRAINT FROM_SIMPLE_TO_PRODUCT FOREIGN KEY (PRODUCT_ID,EXTRA_ID) REFERENCES HTT.PRODUCT
ALTER TABLE HTT.SIMPLE_CUSTOMER_ORDER ADD CONSTRAINT FROM_SIMPLE_TO_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES HTT.CUSTOMER
CREATE TABLE HTT.LINE_ITEM (CUSTOMER_ID_REF VARCHAR(256) NOT NULL, ORDER_NUMBER FLOAT NOT NULL, PRODUCT_ID VARCHAR(256) NOT NULL, EXTRA_PROD_ID VARCHAR(256) NOT NULL, QUANTITY FLOAT, PRIMARY KEY (CUSTOMER_ID_REF, ORDER_NUMBER, PRODUCT_ID, EXTRA_PROD_ID))
CREATE TABLE HTT.CUSTOMER_ORDER (CUSTOMER_ID VARCHAR(256) NOT NULL, ORDER_NUMBER FLOAT NOT NULL, ORDER_DATE DATE NOT NULL, PRIMARY KEY (CUSTOMER_ID, ORDER_NUMBER))                
ALTER TABLE HTT.LINE_ITEM ADD CONSTRAINT TO_CUSTOMER_ORDER FOREIGN KEY (CUSTOMER_ID_REF, ORDER_NUMBER) REFERENCES HTT.CUSTOMER_ORDER
ALTER TABLE HTT.LINE_ITEM ADD CONSTRAINT TO_PRODUCT FOREIGN KEY (PRODUCT_ID, EXTRA_PROD_ID) REFERENCES HTT.PRODUCT
ALTER TABLE HTT.CUSTOMER_ORDER ADD CONSTRAINT TO_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES HTT.CUSTOMER                
