CREATE SCHEMA HTT
CREATE TABLE HTT.CATEGORY (ID INT, PARENT_ID NUMERIC(5))
CREATE TABLE HTT.BAD_TYPE (ID INT, NAME VARCHAR(100))
CREATE SEQUENCE HTT.SHOULD_BE_THERE START WITH 1
CREATE TABLE HTT.HILO_TABLE (ID INT)
