ALTER TABLE LINE_ITEM DROP FOREIGN KEY TO_CUSTOMER_ORDER
ALTER TABLE LINE_ITEM DROP FOREIGN KEY TO_PRODUCT
ALTER TABLE CUSTOMER_ORDER DROP FOREIGN KEY TO_CUSTOMER
ALTER TABLE SIMPLE_LINE_ITEM DROP FOREIGN KEY TO_SIMPLE_CUSTOMER_ORDER
ALTER TABLE SIMPLE_LINE_ITEM DROP FOREIGN KEY FROM_SIMPLE_TO_PRODUCT
ALTER TABLE SIMPLE_CUSTOMER_ORDER DROP FOREIGN KEY FROM_SIMPLE_TO_CUSTOMER
DROP TABLE SIMPLE_LINE_ITEM
DROP TABLE PRODUCT
DROP TABLE CUSTOMER
DROP TABLE SIMPLE_CUSTOMER_ORDER
DROP TABLE CUSTOMER_ORDER                
DROP TABLE LINE_ITEM                           
