package org.hibernate.tool.orm.jbt.api;

import java.util.Iterator;
import java.util.List;

import org.hibernate.mapping.Join;
import org.hibernate.mapping.PersistentClass;
import org.hibernate.mapping.Property;
import org.hibernate.mapping.Subclass;
import org.hibernate.mapping.Table;
import org.hibernate.mapping.Value;
import org.hibernate.tool.orm.jbt.wrp.Wrapper;

public interface PersistentClassWrapper extends Wrapper {

	boolean isAssignableToRootClass();
	boolean isRootClass();
	boolean isInstanceOfRootClass();
	boolean isInstanceOfSubclass();
	boolean isInstanceOfJoinedSubclass();
	Property getProperty();
	void setTable(Table table);
	void setIdentifier(Value value);
	void setKey(Value value);
	boolean isInstanceOfSpecialRootClass();
	Property getParentProperty();
	void setIdentifierProperty(Property property);
	void setDiscriminator(Value value);
	boolean isLazyPropertiesCacheable();
	Iterator<Property> getPropertyIterator();
	Iterator<Join> getJoinIterator();
	Iterator<Subclass> getSubclassIterator();
	Iterator<Property> getPropertyClosureIterator();
	String getEntityName();
	String getClassName();
	Property getIdentifierProperty();
	boolean hasIdentifierProperty();
	PersistentClass getRootClass();
	PersistentClass getSuperclass();
	Property getProperty(String name);
	Table getTable();
	Boolean isAbstract();
	Value getDiscriminator();
	Value getIdentifier();
	Property getVersion();
	void setClassName(String name);
	void setEntityName(String name);
	void setDiscriminatorValue(String str);
	void setAbstract(Boolean b);
	void addProperty(Property p);
	void setProxyInterfaceName(String name);
	void setLazy(boolean b);
	boolean isCustomDeleteCallable();
	boolean isCustomInsertCallable();
	boolean isCustomUpdateCallable();
	boolean isDiscriminatorInsertable();
	boolean isDiscriminatorValueNotNull();
	boolean isDiscriminatorValueNull();
	boolean isExplicitPolymorphism();
	boolean isForceDiscriminator();
	boolean isInherited();
	boolean isJoinedSubclass();
	boolean isLazy();
	boolean isMutable();
	boolean isPolymorphic();
	boolean isVersioned();
	int getBatchSize();
	String getCacheConcurrencyStrategy();
	String getCustomSQLDelete();
	String getCustomSQLInsert();
	String getCustomSQLUpdate();
	String getDiscriminatorValue();
	String getLoaderName();
	int getOptimisticLockMode();
	String getWhere();
	Table getRootTable();
	List<Property> getProperties();
	List<Join> getJoins();
	List<Subclass> getSubclasses();
	List<Property> getPropertyClosure();
	
}
