package org.hibernate.tool.proxies;

/**
 * This bean demonstrates the equals method generated by hbm2java before the change to the
 * equals implementation demonstrated in {@link EqualBean2}. Hbm2java previously used
 * instanceof to check the class of the 'other' parameter, but this doesn't work correctly in the
 * presence of the proxies that Hibernate uses when lazy loading.
 * @author karlvr
 *
 */
public class EqualBean implements EqualBeanProxy {

	private int id;
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/**
	 * The equals implementation previously generated by hbm2java.
	 */
	public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EqualBean) ) return false;
		 EqualBean castOther = ( EqualBean ) other; 
        
		 return (this.getId()==castOther.getId());
  }
  
  public int hashCode() {
        int result = 17;
        
        result = 37 * result + (int) this.getId();
        
        
        
        
        
        
        
        return result;
  }  
}
