CREATE USER OVRTEST IDENTIFIED BY OVRTEST 
GRANT ALL PRIVILEGES TO OVRTEST WITH ADMIN OPTION
CREATE TABLE OVRTEST.CATMASTER ( ID CHAR NOT NULL, NAME VARCHAR(20), PRIMARY KEY (ID) )
CREATE TABLE OVRTEST.CATCHILD  ( CHILDID CHAR NOT NULL, MASTERREF CHAR, PRIMARY KEY (CHILDID), FOREIGN KEY (MASTERREF) REFERENCES OVRTEST.CATMASTER(ID) )
CREATE TABLE MASTER ( ID CHAR NOT NULL, NAME VARCHAR(20), PRIMARY KEY (ID) )
CREATE TABLE CHILD  ( CHILDID CHAR NOT NULL, MASTERREF CHAR, PRIMARY KEY (CHILDID), FOREIGN KEY (MASTERREF) REFERENCES MASTER(ID) )			
