CREATE SCHEMA HTT
CREATE TABLE HTT.VERY_SIMPLE_TABLE ( ID INT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID) )
INSERT INTO HTT.VERY_SIMPLE_TABLE VALUES ( 1, 'A Row')
INSERT INTO HTT.VERY_SIMPLE_TABLE VALUES ( 2, 'Another Row')
