CREATE SCHEMA OTHERSCHEMA
CREATE SCHEMA THIRDSCHEMA
    CREATE TABLE PUBLIC.MEMBER ( ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY(ID))
    CREATE TABLE OTHERSCHEMA.ROLE ( ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY(ID))
    CREATE TABLE THIRDSCHEMA.MEMBERROLE ( MEMBERID INT NOT NULL, ROLEID INT NOT NULL, PRIMARY KEY(MEMBERID, ROLEID))
ALTER TABLE THIRDSCHEMA.MEMBERROLE ADD CONSTRAINT TOROLES FOREIGN KEY (ROLEID) REFERENCES OTHERSCHEMA.ROLE(ID)
ALTER TABLE THIRDSCHEMA.MEMBERROLE ADD CONSTRAINT TOUSERS FOREIGN KEY (MEMBERID) REFERENCES PUBLIC.MEMBER(ID)
CREATE TABLE PLAINROLE ( ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY(ID))
CREATE TABLE PLAINMEMBERROLE ( MEMBERID INT NOT NULL, ROLEID INT NOT NULL, PRIMARY KEY(MEMBERID, ROLEID))
ALTER TABLE PLAINMEMBERROLE ADD CONSTRAINT PLAINTOROLES FOREIGN KEY (ROLEID) REFERENCES PUBLIC.PLAINROLE(ID)
ALTER TABLE PLAINMEMBERROLE ADD CONSTRAINT PLAINTOMEMBERS FOREIGN KEY (MEMBERID) REFERENCES PUBLIC.MEMBER(ID)
