DROP TABLE HTT.PLAINUSERROLES
DROP TABLE HTT.PLAINROLE
DROP TABLE THIRDSCHEMA.USERROLES
DROP TABLE HTT.USERS
DROP TABLE OTHERSCHEMA.ROLE
DROP SCHEMA OTHERSCHEMA
DROP SCHEMA THIRDSCHEMA
DROP SCHEMA HTT
