DROP TABLE HTT.LINE_ITEM                           
DROP TABLE HTT.CUSTOMER_ORDER                
DROP TABLE HTT.SIMPLE_LINE_ITEM
DROP TABLE HTT.SIMPLE_CUSTOMER_ORDER
DROP TABLE HTT.PRODUCT
DROP TABLE HTT.CUSTOMER
DROP SCHEMA HTT
