CREATE SCHEMA HTT
CREATE TABLE HTT.MASTER ( ID CHAR NOT NULL, NAME VARCHAR(20), PRIMARY KEY (ID) )
CREATE TABLE HTT.CHILD  ( CHILDID CHAR NOT NULL, MASTERREF CHAR, PRIMARY KEY (CHILDID), FOREIGN KEY (MASTERREF) REFERENCES HTT.MASTER(ID) )