CREATE TABLE BASIC ( A INT NOT NULL, PRIMARY KEY (A) )
CREATE TABLE SOMECOLUMNSNOPK ( PK VARCHAR(25) NOT NULL, B CHAR, C INT NOT NULL )
CREATE TABLE MULTIKEYED ( ORDERID VARCHAR(10), CUSTOMERID VARCHAR(10), NAME VARCHAR(10), PRIMARY KEY (ORDERID, CUSTOMERID) )
CREATE VIEW BASICVIEW AS SELECT A FROM BASIC
CREATE SYNONYM WEIRDNAME FOR MULTIKEYED
COMMENT ON TABLE BASIC IS 'a basic comment'
COMMENT ON COLUMN BASIC.A IS 'a solid key'
